
-- PROJETO: Kinobresa — Sistema de Gestão de Laticínios
-- BANCO: Firebird 4.0
-- AUTOR: Matheus Bachmann
-- DESCRIÇÃO: Sistema ERP de laticínios em Firebird, cobrindo
     --      fornecedores, produção, estoque, vendas e fiscal.

-- ─── GERADORES (Sequences no Firebird)

CREATE GENERATOR gen_fornecedor;
SET GENERATOR gen_fornecedor TO 0;

CREATE GENERATOR gen_materia_prima;
SET GENERATOR gen_materia_prima TO 0;

CREATE GENERATOR gen_producao;
SET GENERATOR gen_producao TO 0;

CREATE GENERATOR gen_produto;
SET GENERATOR gen_produto TO 0;

CREATE GENERATOR gen_estoque;
SET GENERATOR gen_estoque TO 0;

CREATE GENERATOR gen_cliente;
SET GENERATOR gen_cliente TO 0;

CREATE GENERATOR gen_pedido;
SET GENERATOR gen_pedido TO 0;

CREATE GENERATOR gen_pedido_item;
SET GENERATOR gen_pedido_item TO 0;

CREATE GENERATOR gen_nota;
SET GENERATOR gen_nota TO 0;

-- ─── TABELAS ──────────────────────────────────────────────────

CREATE TABLE TB_FORNECEDOR (
    ID_FORNECEDOR   INTEGER        NOT NULL PRIMARY KEY,
    NOME            VARCHAR(100)   NOT NULL,
    CNPJ_CPF        VARCHAR(18)    NOT NULL,
    TELEFONE        VARCHAR(20),
    CIDADE          VARCHAR(80),
    UF              CHAR(2)        DEFAULT 'PR',
    ATIVO           CHAR(1)        DEFAULT 'S' CHECK (ATIVO IN ('S','N')),
    DT_CADASTRO     DATE           DEFAULT CURRENT_DATE
);

CREATE TABLE TB_MATERIA_PRIMA (
    ID_MP           INTEGER        NOT NULL PRIMARY KEY,
    ID_FORNECEDOR   INTEGER        NOT NULL REFERENCES TB_FORNECEDOR(ID_FORNECEDOR),
    DESCRICAO       VARCHAR(120)   NOT NULL,
    UNIDADE         VARCHAR(10)    NOT NULL,
    PRECO_UNIT      NUMERIC(10,2),
    DT_RECEBIMENTO  DATE           DEFAULT CURRENT_DATE,
    QUANTIDADE      NUMERIC(12,3)  NOT NULL CHECK (QUANTIDADE > 0),
    LOTE_FORNECEDOR VARCHAR(40)
);

CREATE TABLE TB_PRODUCAO (
    ID_PRODUCAO     INTEGER        NOT NULL PRIMARY KEY,
    CODIGO_LOTE     VARCHAR(30)    NOT NULL,
    DT_PRODUCAO     DATE           NOT NULL DEFAULT CURRENT_DATE,
    DT_VALIDADE     DATE           NOT NULL,
    STATUS          VARCHAR(20)    DEFAULT 'ABERTO'
                    CHECK (STATUS IN ('ABERTO','FINALIZADO','CANCELADO')),
    RESPONSAVEL     VARCHAR(100),
    OBSERVACAO      VARCHAR(500)
);

CREATE TABLE TB_PRODUCAO_MP (
    ID_PRODUCAO     INTEGER        NOT NULL REFERENCES TB_PRODUCAO(ID_PRODUCAO),
    ID_MP           INTEGER        NOT NULL REFERENCES TB_MATERIA_PRIMA(ID_MP),
    QUANTIDADE_USADA NUMERIC(12,3) NOT NULL,
    PRIMARY KEY (ID_PRODUCAO, ID_MP)
);

CREATE TABLE TB_PRODUTO (
    ID_PRODUTO      INTEGER        NOT NULL PRIMARY KEY,
    ID_PRODUCAO     INTEGER        NOT NULL REFERENCES TB_PRODUCAO(ID_PRODUCAO),
    DESCRICAO       VARCHAR(150)   NOT NULL,
    TIPO            VARCHAR(50),
    PESO_KG         NUMERIC(8,3),
    PRECO_CUSTO     NUMERIC(10,2),
    PRECO_VENDA     NUMERIC(10,2),
    UNIDADE         VARCHAR(10)    DEFAULT 'UN'
);

CREATE TABLE TB_ESTOQUE (
    ID_ESTOQUE      INTEGER        NOT NULL PRIMARY KEY,
    ID_PRODUTO      INTEGER        NOT NULL REFERENCES TB_PRODUTO(ID_PRODUTO),
    TIPO_MOV        CHAR(1)        NOT NULL CHECK (TIPO_MOV IN ('E','S')),
    QUANTIDADE      NUMERIC(12,3)  NOT NULL CHECK (QUANTIDADE > 0),
    DT_MOVIMENTACAO TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    MOTIVO          VARCHAR(200),
    USUARIO         VARCHAR(60)    DEFAULT CURRENT_USER
);

CREATE TABLE TB_CLIENTE (
    ID_CLIENTE      INTEGER        NOT NULL PRIMARY KEY,
    NOME            VARCHAR(120)   NOT NULL,
    CNPJ_CPF        VARCHAR(18),
    TELEFONE        VARCHAR(20),
    CIDADE          VARCHAR(80),
    UF              CHAR(2)        DEFAULT 'PR',
    ATIVO           CHAR(1)        DEFAULT 'S'
);

CREATE TABLE TB_PEDIDO (
    ID_PEDIDO       INTEGER        NOT NULL PRIMARY KEY,
    ID_CLIENTE      INTEGER        NOT NULL REFERENCES TB_CLIENTE(ID_CLIENTE),
    DT_PEDIDO       DATE           DEFAULT CURRENT_DATE,
    STATUS          VARCHAR(20)    DEFAULT 'ABERTO'
                    CHECK (STATUS IN ('ABERTO','FATURADO','CANCELADO','ENTREGUE')),
    VALOR_TOTAL     NUMERIC(12,2)  DEFAULT 0,
    OBSERVACAO      VARCHAR(400)
);

CREATE TABLE TB_PEDIDO_ITEM (
    ID_ITEM         INTEGER        NOT NULL PRIMARY KEY,
    ID_PEDIDO       INTEGER        NOT NULL REFERENCES TB_PEDIDO(ID_PEDIDO),
    ID_PRODUTO      INTEGER        NOT NULL REFERENCES TB_PRODUTO(ID_PRODUTO),
    QUANTIDADE      NUMERIC(10,3)  NOT NULL CHECK (QUANTIDADE > 0),
    PRECO_UNIT      NUMERIC(10,2)  NOT NULL,
    SUBTOTAL        COMPUTED BY (QUANTIDADE * PRECO_UNIT)
);

CREATE TABLE TB_NOTA_FISCAL (
    ID_NOTA         INTEGER        NOT NULL PRIMARY KEY,
    ID_PEDIDO       INTEGER        NOT NULL REFERENCES TB_PEDIDO(ID_PEDIDO),
    NUMERO_NF       VARCHAR(20)    NOT NULL,
    DT_EMISSAO      DATE           DEFAULT CURRENT_DATE,
    VALOR_TOTAL     NUMERIC(12,2)  NOT NULL,
    STATUS          VARCHAR(20)    DEFAULT 'EMITIDA'
                    CHECK (STATUS IN ('EMITIDA','CANCELADA'))
);

-- ─── ÍNDICES ──────────────────────────────────────────────────

CREATE INDEX IDX_MP_FORNECEDOR  ON TB_MATERIA_PRIMA(ID_FORNECEDOR);
CREATE INDEX IDX_PRODUTO_PROD   ON TB_PRODUTO(ID_PRODUCAO);
CREATE INDEX IDX_ESTOQUE_PROD   ON TB_ESTOQUE(ID_PRODUTO);
CREATE INDEX IDX_PEDIDO_CLI     ON TB_PEDIDO(ID_CLIENTE);
CREATE INDEX IDX_ITEM_PEDIDO    ON TB_PEDIDO_ITEM(ID_PEDIDO);
CREATE INDEX IDX_NF_PEDIDO      ON TB_NOTA_FISCAL(ID_PEDIDO);
